### ISSUE TITLE
Pyvim install on Mac.

### ISSUE THREAD

**Issue by giovannism20** [prompt-toolkit/pyvim#94]
I tried installing pyvim on mac and got the following message :

Installing collected packages: pygments, six, wcwidth, prompt-toolkit, pyflakes, docopt, pyvim
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pygments'

**Comment by lschumm** [comment]
This isn't an issue with Pyvim; this is how `pip` installs work. Since you aren't in a VM, it's attempting to install `pyvim` globally by default---meaning that you'll need root user permissions. To install it globally, run it with `sudo` like so:

```
sudo -H pip install pyvim
```

(here the `-H` flag means that your home directory will be your users', not the root users'; good practice in pip installs).

Another method is through [virtualenvs](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/). Once within a virtualenv, you may use `pip` without root user permissions.
